kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: <ROLE-NAME>
  namespace: <NAMESPACE>
subjects:
- kind: User
  name: https://iam.ng.bluemix.net/kubernetes#<USER-BLUEMIX-EMAIL>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: <RBAC Role>
  apiGroup: rbac.authorization.k8s.io
